package dcamapi;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : lib/dcam/inc/dcamapi.h:498</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("dcamapi") 
public class DCAM_METADATABLOCKHDR extends StructObject {
	public DCAM_METADATABLOCKHDR() {
		super();
	}
	@CLong 
	@Field(0) 
	public long size() {
		return this.io.getCLongField(this, 0);
	}
	@CLong 
	@Field(0) 
	public DCAM_METADATABLOCKHDR size(long size) {
		this.io.setCLongField(this, 0, size);
		return this;
	}
	/// [in] DCAM_METADATAKIND
	@CLong 
	@Field(1) 
	public long iKind() {
		return this.io.getCLongField(this, 1);
	}
	/// [in] DCAM_METADATAKIND
	@CLong 
	@Field(1) 
	public DCAM_METADATABLOCKHDR iKind(long iKind) {
		this.io.setCLongField(this, 1, iKind);
		return this;
	}
	/// [in] 0 reserved
	@CLong 
	@Field(2) 
	public long option() {
		return this.io.getCLongField(this, 2);
	}
	/// [in] 0 reserved
	@CLong 
	@Field(2) 
	public DCAM_METADATABLOCKHDR option(long option) {
		this.io.setCLongField(this, 2, option);
		return this;
	}
	/// [in] start frame index
	@CLong 
	@Field(3) 
	public long iFrame() {
		return this.io.getCLongField(this, 3);
	}
	/// [in] start frame index
	@CLong 
	@Field(3) 
	public DCAM_METADATABLOCKHDR iFrame(long iFrame) {
		this.io.setCLongField(this, 3, iFrame);
		return this;
	}
	/// [in] max count of meta data
	@CLong 
	@Field(4) 
	public long inCount() {
		return this.io.getCLongField(this, 4);
	}
	/// [in] max count of meta data
	@CLong 
	@Field(4) 
	public DCAM_METADATABLOCKHDR inCount(long inCount) {
		this.io.setCLongField(this, 4, inCount);
		return this;
	}
	/// [out] count of got meta data.
	@CLong 
	@Field(5) 
	public long outcount() {
		return this.io.getCLongField(this, 5);
	}
	/// [out] count of got meta data.
	@CLong 
	@Field(5) 
	public DCAM_METADATABLOCKHDR outcount(long outcount) {
		this.io.setCLongField(this, 5, outcount);
		return this;
	}
	public DCAM_METADATABLOCKHDR(Pointer pointer) {
		super(pointer);
	}
}
